export const LIST_BILLING ='LIST_BILLING'
export const LIST_BILLING_SUCCESS ='LIST_BILLING_SUCCESS'
export const LIST_BILLING_FAILED ='LIST_BILLING_FAILED'

export const DETAIL_BILLING ="DETAIL_BILLING"
export const DETAIL_BILLING_SUCCESS ="DETAIL_BILLING_SUCCESS"
export const DETAIL_BILLING_FAILED ="DETAIL_BILLING_FAILED"

export const CREATE_BILLING ="CREATE_BILLING"
export const CREATE_BILLING_SUCCESS ="CREATE_BILLING_SUCCESS"
export const CREATE_BILLING_FAILED ="CREATE_BILLING_SUCCESS"

export const EDIT_BILLING ='EDIT_BILLING'
export const EDIT_BILLING_SUCCESS ='EDIT_BILLING_SUCCESS'
export const EDIT_BILLING_FAILED ='EDIT_BILLING_FAILED'
