version: "3.8"

services:

  website:

    image: domain-prod/usdc/usdc-website-${CI_ENVIRONMENT_SLUG}:${CI_PIPELINE_ID}
    networks:
      - usdc_network
      - nginx_public
    deploy:
      mode: replicated
      replicas: 1

networks:
  usdc_network:
    attachable: true
  nginx_public:
    external: true
