export const GET_LIST_PRODUCT_CUSTOMER = "GET_LIST_PRODUCT_CUSTOMER";
export const GET_LIST_PRODUCT_CUSTOMER_SUCCESS =
  "GET_LIST_PRODUCT_CUSTOMER_SUCCESS";
export const GET_LIST_PRODUCT_CUSTOMER_FAILED =
  "GET_LIST_PRODUCT_CUSTOMER_FAILED";

export const GET_DETAIL_PRODUCT_CUSTOMER = "GET_DETAIL_PRODUCT_CUSTOMER";
export const GET_DETAIL_PRODUCT_CUSTOMER_SUCCESS =
  "GET_DETAIL_PRODUCT_CUSTOMER_SUCCESS";
export const GET_DETAIL_PRODUCT_CUSTOMER_FAILED =
  "GET_DETAIL_PRODUCT_CUSTOMER_FAILED";

export const DEL_PRODUCT_CUSTOMER = "DEL_PRODUCT_CUSTOMER";
export const DEL_PRODUCT_CUSTOMER_SUCCESS = "DEL_PRODUCT_CUSTOMER_SUCCESS";
export const DEL_PRODUCT_CUSTOMER_FAILED = "DEL_PRODUCT_CUSTOMER_FAILED";

export const POST_PRODUCT_OF_CUSTOMER = "POST_PRODUCT_OF_CUSTOMER";
export const POST_PRODUCT_OF_CUSTOMER_SUCCESS =
  "POST_PRODUCT_OF_CUSTOMER_SUCCESS";
export const POST_PRODUCT_OF_CUSTOMER_FAILED =
  "POST_PRODUCT_OF_CUSTOMER_FAILED";

export const CREATE_PRODUCT_OF_CUSTOMER = "CREATE_PRODUCT_OF_CUSTOMER";
export const CREATE_PRODUCT_OF_CUSTOMER_SUCCESS =
  "CREATE_PRODUCT_OF_CUSTOMER_SUCCESS";
export const CREATE_PRODUCT_OF_CUSTOMER_FAILED =
  "CREATE_PRODUCT_OF_CUSTOMER_FAILED";

  export const UPDATE_PRODUCT_OF_CUSTOMER ="UPDATE_PRODUCT_OF_CUSTOMER"
  export const UPDATE_PRODUCT_OF_CUSTOMER_SUCCESS ="UPDATE_PRODUCT_OF_CUSTOMER_SUCCESS"
  export const UPDATE_PRODUCT_OF_CUSTOMER_FAILED ="UPDATE_PRODUCT_OF_CUSTOMER_FAILED"

  export const DETAIL_PRODUCT_OF_CUSTOMER ='DETAIL_PRODUCT_OF_CUSTOMER'
  export const DETAIL_PRODUCT_OF_CUSTOMER_SUCCESS ='DETAIL_PRODUCT_OF_CUSTOMER_SUCCESS'
  export const DETAIL_PRODUCT_OF_CUSTOMER_FAILED ='DETAIL_PRODUCT_OF_CUSTOMER_FAILED'

export const GET_LIST_CONTRACT_OF_CUSTOMER  ="GET_LIST_CONTRACT_OF_CUSTOMER"
export const GET_LIST_CONTRACT_OF_CUSTOMER_SUCCESS  ="GET_LIST_CONTRACT_OF_CUSTOMER_SUCCESS"
export const GET_LIST_CONTRACT_OF_CUSTOMER_FAILED  ="GET_LIST_CONTRACT_OF_CUSTOMER_FAILED"

export const UPDATE_DETAIL_PRODUCT_OF_CUSTOMER ="UPDATE_DETAIL_PRODUCT_OF_CUSTOMER"
export const UPDATE_DETAIL_PRODUCT_OF_CUSTOMER_SUCCESS ="UPDATE_DETAIL_PRODUCT_OF_CUSTOMER_SUCCESS"
export const UPDATE_DETAIL_PRODUCT_OF_CUSTOMER_FAILED ="UPDATE_DETAIL_PRODUCT_OF_CUSTOMER_FAILED"

