export const GET_LIST_ORDER = "GET_LIST_ORDER";
export const GET_LIST_ORDER_SUCCESS = "GET_LIST_ORDER_SUCCESS";
export const GET_LIST_ORDER_FAILED = "GET_LIST_ORDER_FAILED";

export const DETAIL_ORDER_OF_CUSTOMER = "DETAIL_ORDER_OF_CUSTOMER";
export const DETAIL_ORDER_OF_CUSTOMER_SUCCESS =
  "DETAIL_ORDER_OF_CUSTOMER_SUCCESS";
export const DETAIL_ORDER_OF_CUSTOMER_FAILED =
  "DETAIL_ORDER_OF_CUSTOMER_FAILED";
