export const SITE_STATIC = "SITE_STATIC";
export const SITE_STATIC_SUCCESS = "SITE_STATIC_SUCCESS";
export const SITE_STATIC_FAILED = "SITE_STATIC_FAILED";

export const GET_SATATIC_INFO = 'GET_SATATIC_INFO'
export const GET_SATATIC_INFO_SUCCESS = 'GET_SATATIC_INFO_SUCCESS'
export const GET_SATATIC_INFO_FAILED = 'GET_SATATIC_INFO_FAILED'
