export const ADD_PACKAGE = "ADD_PACKAGE";
export const ADD_PACKAGE_SUCCESS = "ADD_PACKAGE_SUCCESS";
export const ADD_PACKAGE_FAILED = "ADD_PACKAGE_FAILED";

export const GET_LIST_PACKAGE = "GET_LIST_PACKAGE";
export const GET_LIST_PACKAGE_SUCCESS = "GET_LIST_PACKAGE_SUCCESS";
export const GET_LIST_PACKAGE_FAILED = "GET_LIST_PACKAGE_FAILED";

export const DETAIL_PACKAGE = "DETAIL_PACKAGE";
export const DETAIL_PACKAGE_SUCCESS = "DETAIL_PACKAGE_SUCCESS";
export const DETAIL_PACKAGE_FAILED = "DETAIL_PACKAGE_FAILED";

export const EDIT_PACKAGE = "EDIT_PACKAGE";
export const EDIT_PACKAGE_SUCCESS = "EDIT_PACKAGE_SUCCESS";
export const EDIT_PACKAGE_FAILED = "EDIT_PACKAGE_FAILED";

export const UPDATE_PACKAGE ="UPDATE_PACKAGE"
export const UPDATE_PACKAGE_SUCCESS ="UPDATE_PACKAGE_SUCCESS"
export const UPDATE_PACKAGE_FAILED ="UPDATE_PACKAGE_FAILED"


export const LIST_PACKAGE_PRODUCT = "LIST_PACKAGE_PRODUCT";
export const LIST_PACKAGE_PRODUCT_SUCCESS = "LIST_PACKAGE_PRODUCT_SUCCESS";
export const LIST_PACKAGE_PRODUCT_FAILED = "LIST_PACKAGE_PRODUCT_FAILED";
