export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const STATIC_INFO = "STATIC_INFO";
export const STATIC_INFO_SUCCESS = "STATIC_INFO_SUCCESS";
export const STATIC_INFO_FAILED = "STATIC_INFO_FAILED";
export const SET_SHOPPING_CARTS = "SET_SHOPPING_CARTS";

export const FCM_TOKEN = "FCM_TOKEN";
export const FCM_TOKEN_SUCCESS = "FCM_TOKEN_SUCCESS";
export const FCM_TOKEN_FAILED = "FCM_TOKEN_FAILED";

export const COUNT_ALERT = "COUNT_ALERT";
export const COUNT_ALERT_SUCCESS = "COUNT_ALERT_SUCCESS";
export const COUNT_ALERT_FAILED = "COUNT_ALERT_FAILED";
