export const GET_LIST_PRODUCTS = "GET_LIST_PRODUCTS";
export const GET_LIST_PRODUCTS_SUCCESS = "GET_LIST_PRODUCTS_SUCCESS";
export const GET_LIST_PRODUCTS_FAILED = "GET_LIST_PRODUCTS_FAILED";

export const GET_DETAIL_PRODUCTS = "GET_DETAIL_PRODUCTS";
export const GET_DETAIL_PRODUCTS_SUCCESS = "GET_DETAIL_PRODUCTS_SUCCESS";
export const GET_DETAIL_PRODUCTS_FAILED = "GET_DETAIL_PRODUCTS_FAILED";

export const EDIT_DETAIL_PRODUCT = "EDIT_DETAIL_PRODUCT";
export const EDIT_DETAIL_PRODUCT_SUCCESS = "EDIT_DETAIL_PRODUCT_SUCCESS";
export const EDIT_DETAIL_PRODUCT_FAILED = "EDIT_DETAIL_PRODUCT_FAILED";

export const DEL_PRODUCT = "DEL_PRODUCT";
export const DEL_PRODUCT_SUCCESS = "DEL_PRODUCT_SUCCESS";
export const DEL_PRODUCT_FAILED = "DEL_PRODUCT_FAILED";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED";

export const GET_LIST_PRODUCT_OF_CUSTOMER = "GET_LIST_PRODUCT_OF_CUSTOMER";
export const GET_LIST_PRODUCT_OF_CUSTOMER_SUCCESS =
  "GET_LIST_PRODUCT_OF_CUSTOMER_SUCCESS";
export const GET_LIST_PRODUCT_OF_CUSTOMER_FAILED =
  "GET_LIST_PRODUCT_OF_CUSTOMER_FAILED";

export const GET_CATELOG = "GET_CATELOG";
export const GET_CATELOG_SUCCESS = "GET_CATELOG_SUCCESS";
export const GET_CATELOG_FAILED = "GET_CATELOG_FAILED";

export const GET_PRODUCT_OF_CATELOG = "GET_PRODUCT_OF_CATELOG";
export const GET_PRODUCT_OF_CATELOG_SUCCESS = "GET_PRODUCT_OF_CATELOG_SUCCESS";
export const GET_PRODUCT_OF_CATELOG_FAILED = "GET_PRODUCT_OF_CATELOG_FAILED";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
