export const LIST_ALERT_ADMIN = "LIST_ALERT_ADMIN";
export const LIST_ALERT_ADMIN_SUCCESS = "LIST_ALERT_ADMIN_SUCCESS";
export const LIST_ALERT_ADMIN_FAILED = "LIST_ALERT_ADMIN_FAILED";

export const PUT_ALERT_READ ="PUT_ALERT_READ"
export const PUT_ALERT_READ_SUCCESS ="PUT_ALERT_READ_SUCCESS"
export const PUT_ALERT_READ_FAILED ="PUT_ALERT_READ_FAILED"