export const GET_LIST_CATELOG = "GET_LIST_CATELOG";
export const GET_LIST_CATELOG_SUCCESS = "GET_LIST_CATELOG_SUCCESS";
export const GET_LIST_CATELOG_FAILED = "GET_LIST_CATELOG_FAILED";

export const DEL_LIST_CATELOG = "DEL_LIST_CATELOG";
export const DEL_LIST_CATELOG_SUCCESS = "DEL_LIST_CATELOG_SUCCESS";
export const DEL_LIST_CATELOG_FAILED = "DEL_LIST_CATELOG_FAILED";

export const ADD_LIST_CATELOG = "ADD_LIST_CATELOG";
export const ADD_LIST_CATELOG_SUCCESS = "ADD_LIST_CATELOG_SUCCESS";
export const ADD_LIST_CATELOG_FAILED = "ADD_LIST_CATELOG_FAILED";

export const DETAIL_CATELOG = "DETAIL_CATELOG";
export const DETAIL_CATELOG_SUCCESS = "DETAIL_CATELOG_SUCCESS";
export const DETAIL_CATELOG_FAILED = "DETAIL_CATELOG_FAILED";

export const UPDATE_CATELOG = "UPDATE_CATELOG";
export const UPDATE_CATELOG_SUCCESS = "UPDATE_CATELOG_SUCCESS";
export const UPDATE_CATELOG_FAILED = "UPDATE_CATELOG_FAILED";
