export const GET_LIST_CUSTOMER = "GET_LIST_CUSTOMER";
export const GET_LIST_CUSTOMER_SUCCESS = "GET_LIST_CUSTOMER_SUCCESS";
export const GET_LIST_CUSTOMER_FAILED = "GET_LIST_CUSTOMER_FAILED";

export const GET_DETAIL_CUSTOMER = "GET_DETAIL_CUSTOMER";
export const GET_DETAIL_CUSTOMER_SUCCESS = "GET_DETAIL_CUSTOMER_SUCCESS";
export const GET_DETAIL_CUSTOMER_FAILED = "GET_DETAIL_CUSTOMER_FAILED";

export const EDIT_DETAIL_CUSTOMER = "EDIT_DETAIL_CUSTOMER";
export const EDIT_DETAIL_CUSTOMER_SUCCESS = "EDIT_DETAIL_CUSTOMER_SUCCESS";
export const EDIT_DETAIL_CUSTOMER_FAILED = "EDIT_DETAIL_CUSTOMER_FAILED";

export const GET_DETAIL_ACCOUNT_CUSTOMER = "GET_DETAIL_ACCOUNT_CUSTOMER";
export const GET_DETAIL_ACCOUNT_CUSTOMER_SUCCESS =
  "GET_DETAIL_ACCOUNT_CUSTOMER_SUCCESS";
export const GET_DETAIL_ACCOUNT_CUSTOMER_FAILED =
  "GET_DETAIL_ACCOUNT_CUSTOMER_FAILED";

export const DEL_CUSTOMER = "DEL_CUSTOMER";
export const DEL_CUSTOMER_SUCCESS = "DEL_CUSTOMER_SUCCESS";
export const DEL_CUSTOMER_FAILED = "DEL_CUSTOMER_FAILED";

export const GET_ROLE = "GET_ROLE";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_FAILED = "GET_ROLE_FAILED";

export const GET_LIST_CUSTOMER_ACCOUNT = "GET_LIST_CUSTOMER_ACCOUNT";
export const GET_LIST_CUSTOMER_ACCOUNT_SUCCESS =
  "GET_LIST_CUSTOMER_ACCOUNT_SUCCESS";
export const GET_LIST_CUSTOMER_ACCOUNT_FAILED =
  "GET_LIST_CUSTOMER_ACCOUNT_FAILED";

export const UPDATE_DETAIL_CUSTOMER_ACCOUNT = "UPDATE_DETAIL_CUSTOMER_ACCOUNT";
export const UPDATE_DETAIL_CUSTOMER_ACCOUNT_SUCCESS =
  "UPDATE_DETAIL_CUSTOMER_ACCOUNT_SUCCESS";
export const UPDATE_DETAIL_CUSTOMER_ACCOUNT_FAILED =
  "UPDATE_DETAIL_CUSTOMER_ACCOUNT_FAILED";

export const DEL_DETAIL_CUSTOMER_ACCOUNT = "DEL_DETAIL_CUSTOMER_ACCOUNT";
export const DEL_DETAIL_CUSTOMER_ACCOUNT_SUCCESS =
  "DEL_DETAIL_CUSTOMER_ACCOUNT_SUCCESS";
export const DEL_DETAIL_CUSTOMER_ACCOUNT_FAILED =
  "DEL_DETAIL_CUSTOMER_ACCOUNT_FAILED";

export const LIST_ACCOUNT_OF_CUSTOMER = "LIST_ACCOUNT_OF_CUSTOMER";
export const LIST_ACCOUNT_OF_CUSTOMER_SUCCESS =
  "LIST_ACCOUNT_OF_CUSTOMER_SUCCESS";
export const LIST_ACCOUNT_OF_CUSTOMER_FAILED =
  "LIST_ACCOUNT_OF_CUSTOMER_FAILED";

export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILED = "ADD_CUSTOMER_FAILED";

export const ADD_CUSTOMER_ACCOUNT = "ADD_CUSTOMER_ACCOUNT";
export const ADD_CUSTOMER_ACCOUNT_SUCCESS = "ADD_CUSTOMER_ACCOUNT_SUCCESS";
export const ADD_CUSTOMER_ACCOUNT_FAILED = "ADD_CUSTOMER_ACCOUNT_FAILED";
