export const GET_LIST_CONTRACT = "GET_LIST_CONTRACT";
export const GET_LIST_CONTRACT_SUCCESS = "GET_LIST_CONTRACT_SUCCESS";
export const GET_LIST_CONTRACT_FAILED = "GET_LIST_CONTRACT_FAILED";

export const GET_DETAIL_CONTRACT = "GET_DETAIL_CONTRACT";
export const GET_DETAIL_CONTRACT_SUCCESS = "GET_DETAIL_CONTRACT_SUCCESS";
export const GET_DETAIL_CONTRACT_FAILED = "GET_DETAIL_CONTRACT_FAILED";
