export const GET_LIST_ORDER_CUSTOMER = "GET_LIST_ORDER_CUSTOMER";
export const GET_LIST_ORDER_CUSTOMER_SUCCESS =
  "GET_LIST_ORDER_CUSTOMER_SUCCESS";
export const GET_LIST_ORDER_CUSTOMER_FAILED = "GET_LIST_ORDER_CUSTOMER_FAILED";

export const GET_DETAIL_ORDER_CUSTOMER = "GET_DETAIL_ORDER_CUSTOMER";
export const GET_DETAIL_ORDER_CUSTOMER_SUCCESS =
  "GET_DETAIL_ORDER_CUSTOMER_SUCCESS";
export const GET_DETAIL_ORDER_CUSTOMER_FAILED =
  "GET_DETAIL_ORDER_CUSTOMER_FAILED";

export const DEL_ORDER_CUSTOMER = "DEL_ORDER_CUSTOMER";
export const DEL_ORDER_CUSTOMER_SUCCESS = "DEL_ORDER_CUSTOMER_SUCCESS";
export const DEL_ORDER_CUSTOMER_FAILED = "DEL_ORDER_CUSTOMER_FAILED";

export const CREATE_CONTRACT = "CREATE_CONTRACT";
export const CREATE_CONTRACT_SUCCESS = "CREATE_CONTRACT_SUCCESS";
export const CREATE_CONTRACT_FAILED = "CREATE_CONTRACT_FAILED";
