export const INITIAL_HOME_SCREEN = "INITIAL_HOME_SCREEN";
export const GET_MENU = "GET_MENU";
export const GET_PAGE = "GET_PAGE";
export const GET_PAGE_REQUEST = "GET_PAGE_REQUEST";
export const GET_DETAIL = "GET_DETAIL";
export const REFRESH_PAGE = "REFRESH_PAGE";

export const INFO_CUSTOMER = "INFO_CUSTOMER";
export const INFO_CUSTOMER_SUCCESS = "INFO_CUSTOMER_SUCCESS";
export const INFO_CUSTOMER_FAILED = "INFO_CUSTOMER_FAILED";

export const GET_COUNT_ADMIN = "GET_COUNT_ADMIN";
export const GET_COUNT_ADMIN_SUCCESS = "GET_COUNT_ADMIN_SUCCESS";
export const GET_COUNT_ADMIN_FAILED = "GET_COUNT_ADMIN_SUCCESS";

export const GET_COUNT_CUSTOMER = "GET_COUNT_CUSTOMER";
export const GET_COUNT_CUSTOMER_SUCCESS = "GET_COUNT_CUSTOMER_SUCCESS";
export const GET_COUNT_CUSTOMER_FAILED = "GET_COUNT_CUSTOMER_FAILED";

export const GET_COUNT_TICKET_ADMIN = "GET_COUNT_TICKET_ADMIN";
export const GET_COUNT_TICKET_ADMIN_SUCCESS = "GET_COUNT_TICKET_ADMIN_SUCCESS";
export const GET_COUNT_TICKET_ADMIN_FAILED = "GET_COUNT_TICKET_ADMIN_FAILED";

export const GET_COUNT_TICKET_CUSTOMER = "GET_COUNT_TICKET_CUSTOMER";
export const GET_COUNT_TICKET_CUSTOMER_SUCCESS =
  "GET_COUNT_TICKET_CUSTOMER_SUCCESS";
export const GET_COUNT_TICKET_CUSTOMER_FAILED =
  "GET_COUNT_TICKET_CUSTOMER_FAILED";

export const GET_LIST_PRODUCT_SERVICES_ADMIN =
  "GET_LIST_PRODUCT_SERVICES_ADMIN";
export const GET_LIST_PRODUCT_SERVICES_ADMIN_SUCCESS =
  "GET_LIST_PRODUCT_SERVICES_ADMIN_SUCCESS";
export const GET_LIST_PRODUCT_SERVICES_ADMIN_FAILED =
  "GET_LIST_PRODUCT_SERVICES_ADMIN_FAILED";

export const GET_LIST_PRODUCT_SERVICES_CUSTOMER =
  "GET_LIST_PRODUCT_SERVICES_CUSTOMER";
export const GET_LIST_PRODUCT_SERVICES_CUSTOMER_SUCCESS =
  "GET_LIST_PRODUCT_SERVICES_CUSTOMER_SUCCESS";
export const GET_LIST_PRODUCT_SERVICES_CUSTOMER_FAILED =
  "GET_LIST_PRODUCT_SERVICES_CUSTOMER_FAILED";

  export const GET_LIST_CUSTOMER_OF_PRODUCT_ADMIN =
  "GET_LIST_CUSTOMER_OF_PRODUCT_ADMIN";
  export const GET_LIST_CUSTOMER_OF_PRODUCT_ADMIN_SUCCESS =
  "GET_LIST_CUSTOMER_OF_PRODUCT_ADMIN_SUCCESS";
  export const GET_LIST_CUSTOMER_OF_PRODUCT_ADMIN_FAILED =
  "GET_LIST_CUSTOMER_OF_PRODUCT_ADMIN_FAILED";

  export const PACKAGE_OF_PRODUCT_CUSTOMER ='PACKAGE_OF_PRODUCT_CUSTOMER';
  export const PACKAGE_OF_PRODUCT_CUSTOMER_SUCCESS ='PACKAGE_OF_PRODUCT_CUSTOMER_SUCCESS';
  export const PACKAGE_OF_PRODUCT_CUSTOMER_FAILED ='PACKAGE_OF_PRODUCT_CUSTOMER_FAILED'

  export const GET_BALANCE ='GET_BALANCE'
  export const GET_BALANCE_SUCCESS ='GET_BALANCE_SUCCESS'
  export const GET_BALANCE_FAILED ='GET_BALANCE_FAILED'
